apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    env: qa
spec:
  minReadySeconds: 10s
  replicas: 3
  selector:
    matchLabels:
      name: deplo
  template:
    metadata:
      name: deplo
    spec:
      containers:
        - image: nginx:latest
          name: nginx Deployment
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"