#to create name for the deployment which we are creating we need to use below command
#kubectl create/apply -f nginix.yam --namespace="<name-space which we created already or new space with this command can be created>"
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    env: qa
spec:
  minReadySeconds: 10
  replicas: 3
  selector:
    matchLabels:
      env: qa
  template:
    metadata:
      labels:
        env: qa
    spec:
      containers:
        - image: nginx:latest
          name: nginx-deployment
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"

======
apiVersion: v1
kind: Service
metadata:
  name: service
  labels:
  env: qa
spec:
  selector:
    matchLabels:
      env: qa
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
